name: package upgrade

on: [push]
  # schedule:
  #   - cron: '0 4 * * 0' # sunday at 13:00 (UTF+9)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install npm-check-updates
        run: |
          git config user.name 'yoshihara'
          git config user.email '594134+yoshihara@users.noreply.github.com'
          npm install -g npm-check-updates

      - name: run ncu
        id: ncu
        run: |
          echo "##[set-output name=ncu-upgrade;]$(ncu -u)"

      - name: run npm install
        run: |
          npm install

      - name: diff existing check
        id: check
        run: |
          [ `git diff | wc -l` = 0 ]
        continue-on-error: true

      - name: create commit
        id: commit
        run: |
          git add package.json package-lock.json
          git commit -m "Update npm packages"
        if: steps.check.outcome == 'failure' # failure = diff がある場合
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: upgrade npm packages
          body: |
            Run with GitHub Actions.

            Outputs:

            ```
            ${{ steps.ncu.outputs.ncu-upgrade}}
            ```
          branch: update-npm-packages-with-ncu
        if: steps.commit.outcome == 'success' # 1つ上のstepが成功した=commitがあるということなのでPRを作る
