name: package upgrade

on: [push]
  # schedule:
  #   - cron: '0 4 * * 0' # sunday at 13:00 (UTF+9)

jobs:
  package-upgrade:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm-check-updates
        run: |
          npm install -g npm-check-updates

      - name: Run ncu
        id: ncu
        run: |
          # https://github.community/t/set-output-truncates-multiline-strings/16852/3
          text="`ncu -u 2> /dev/null`"
          text="${text//'%'/'%25'}"
          text="${text//$'\n'/'%0A'}"
          text="${text//$'\r'/'%0D'}"
          echo $text
          echo "::set-output name=ncu-upgrade::$text"
      - name: Run npm install
        run: |
          npm install

      - name: Check diff existing
        id: check
        run: |
          [ `git diff | wc -l` = 0 ]
        continue-on-error: true

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          title: Upgrade npm packages
          body: |
            This PR was created by GitHub Actions.

            Outputs:

            ```
            ${{ steps.ncu.outputs.ncu-upgrade }}
            ```
          branch: update-npm-packages-with-ncu
          commit-message: "Update npm packages"
          commiter: "yoshihara <594134+yoshihara@users.noreply.github.com"
          author: "yoshihara <594134+yoshihara@users.noreply.github.com"

        if: steps.check.outcome == 'failure' # failure = diff がある場合
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
