name: package upgrade

on: [push]
  # schedule:
  #   - cron: '0 4 * * 0' # sunday at 13:00 (UTF+9)

jobs:
  package-upgrade:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm-check-updates
        run: |
          npm install -g npm-check-updates

      - name: Run ncu
        id: ncu
        run: |
          text="`ncu -u 2> /dev/null`"

          # https://github.community/t/set-output-truncates-multiline-strings/16852/3
          text="${text//'%'/'%25'}"
          text="${text//$'\n'/'%0A'}"
          text="${text//$'\r'/'%0D'}"
          echo $text
          echo "::set-output name=ncu-upgrade::$text"

      - name: Check diff existing
        id: check
        run: |
          [ `git diff | wc -l` = 0 ]
        continue-on-error: true

      - name: Run npm install
        run: |
          npm install

      - name: do nothing
        run: |
          git status
        if: steps.check.outcome == 'success' # success = アップグレードされたパッケージがない

      - name: Create commit
        id: commit
        run: |
          git config user.name 'yoshihara'
          git config user.email '594134+yoshihara@users.noreply.github.com'
          git checkout -b update-npm-packages-with-ncu
          git add package.json package-lock.json
          git commit -m "Update npm packages"
          git push origin update-npm-packages-with-ncu
        if: steps.check.outcome == 'failure' # failure = アップグレードされたパッケージがある

      - name: Create Pull Request
        id: create-pr
        run: |
          text="${{ steps.ncu.outputs.ncu-upgrade }}"

          # ただの改行になっているのでエスケープした文字にする
          text="${text//$'\n'/'\n'}"
          text="${text//$'\r'/'\r'}"
          text="This PR was created by GitHub Actions.\\n\\nOutputs:\\n\\n\`\`\`\\n${text}\\n\`\`\`\\n\\nStatus:\\n\\n![package upgrade](https://github.com/yoshihara/tsuibami/workflows/package%20upgrade/badge.svg)"
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "{
            \"title\": \"Upgrade npm packages\",
            \"body\": \"${text}\",
            \"head\": \"update-npm-packages-with-ncu\",
            \"base\": \"master\"
            }"

        if: steps.check.outcome == 'failure'

      - name: RUN test
        run: |
          npm test
        env:
          CI: true
        if: steps.check.outcome == 'failure'
